# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 03:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_bankaccount_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 4, 3, 34, 36, 724285, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 4, 3, 34, 44, 172224, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
