# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cp',
            field=models.BigIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credits',
            field=models.BigIntegerField(default=10),
        ),
    ]
