# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20160801_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
