# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 03:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_auto_20160801_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 4, 3, 34, 28, 558993, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
