# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
