# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forum_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='forum_banned_reason',
            field=models.TextField(null=True),
        ),
    ]
