# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-02 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_profile_forum_banned_lifted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.IntegerField(),
        ),
    ]
